-- Phase 2: question types + streak freeze columns
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TRANSLATE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'LISTEN';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MATCH';

ALTER TABLE "Streak" ADD COLUMN IF NOT EXISTS "freezesAvailable" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Streak" ADD COLUMN IF NOT EXISTS "freezesUsed" INTEGER NOT NULL DEFAULT 0;
