import type { PublicLesson } from "../../lib/api";
import type { AuthUser, StreakSummary } from "../../lib/api";

/** Visual-QA fixtures for `?demo=1` (no API / no trademarks). */
export const DEMO_USER: AuthUser = {
  id: "demo-user",
  email: "demo@walky-talky.app",
  displayName: "Demo Learner",
  timezone: "UTC",
  xp: 240,
  level: 3,
  hearts: 4,
  dailyXpGoal: 50,
};

export const DEMO_STREAK: StreakSummary = {
  currentStreak: 5,
  longestStreak: 12,
  lastActiveDate: null,
  todayXp: 30,
  dailyXpGoal: 50,
  goalMet: false,
  freezesAvailable: 1,
  freezesUsed: 0,
};

export const DEMO_LESSONS: PublicLesson[] = [
  {
    id: "l1",
    slug: "greetings",
    title: "Greetings",
    description: "Hello, goodbye, and polite basics",
    unitOrder: 1,
    lessonOrder: 1,
    xpReward: 20,
    estimatedMinutes: 5,
    locked: false,
    completed: true,
    stars: 3,
  },
  {
    id: "l2",
    slug: "numbers-1",
    title: "Numbers 1–5",
    description: "Count from one to five",
    unitOrder: 1,
    lessonOrder: 2,
    xpReward: 20,
    estimatedMinutes: 5,
    locked: false,
    completed: true,
    stars: 2,
  },
  {
    id: "l3",
    slug: "phrases-lab",
    title: "Phrases Lab",
    description: "Translate, listen, and match",
    unitOrder: 1,
    lessonOrder: 3,
    xpReward: 20,
    estimatedMinutes: 6,
    locked: false,
    completed: false,
    stars: 0,
    hasActiveSession: true,
  },
  {
    id: "l4",
    slug: "food-basics",
    title: "Food Basics",
    description: "Common food words",
    unitOrder: 2,
    lessonOrder: 1,
    xpReward: 20,
    estimatedMinutes: 5,
    locked: true,
    completed: false,
    stars: 0,
  },
  {
    id: "l5",
    slug: "colors",
    title: "Colors",
    description: "Basic color words",
    unitOrder: 2,
    lessonOrder: 2,
    xpReward: 20,
    estimatedMinutes: 5,
    locked: true,
    completed: false,
    stars: 0,
  },
];
